notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
install: false
services:
  - docker
dist: xenial
python: 3
addons:
  apt:
    update: true
    packages:
      - jq
      - zip
      - curl
      - bash
      - unzip
      - docker-ce
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools
before_install:
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - sdk use gradle 5.5-rc-2
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
  - pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  - http --version --debug
  - docker-compose -v
  #
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 5432 5672 27017 8080 8000 8081 80 80
before_script:
  - ./gradlew up
after_script:
  - ./gradlew rm
jobs:
  include:
    # java 8
    - stage: openjdk8
      jdk: openjdk8
      name: "Gradle Java 8 Build"
      script:
        - cd $TRAVIS_BUILD_DIR
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-gradle.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - sleep 5s
        - ./gradlew flywayClean
        - ./gradlew flywayMigrate
        - ./gradlew test
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-jar.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - ./gradlew assemble
        - java -jar build/libs/*-SNAPSHOT.jar &
        - wait_for 8080
        - http :8080/employees name=ololo
        - http :8080/employees name=trololo salary=12345
        - http :8080/employees
        - stop_any 80 8080
    - stage: openjdk8
      jdk: openjdk8
      name: "Gradle Java 8 Updates"
      script: cd $TRAVIS_BUILD_DIR && gradle :wrapper && ./gradlew dependencyUpdates -Drevision=release
    # java 11
    - stage: openjdk11
      jdk: openjdk11
      name: "Gradle Java 11 Build"
      script:
        - cd $TRAVIS_BUILD_DIR
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-gradle.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - sleep 5s
        - ./gradlew flywayClean
        - ./gradlew flywayMigrate
        - ./gradlew test
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-jar.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - ./gradlew assemble
        - java -jar build/libs/*-SNAPSHOT.jar &
        - wait_for 8080
        - http :8080/employees name=ololo
        - http :8080/employees name=trololo salary=12345
        - http :8080/employees
        - stop_any 80 8080
    - stage: openjdk11
      jdk: openjdk11
      name: "Gradle Java 11 Updates"
      script: cd $TRAVIS_BUILD_DIR ; gradle :wrapper ; ./gradlew dependencyUpdates -Drevision=release
cache:
  directories:
    - ~/.docker
    - ~/.gradle
    - ~/.m2
  packages: true
  pip: true
