notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
install: true
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - zip
      - unzip
      - curl
      - bash
before_install:
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk selfupdate
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - sdk use gradle 5.5-rc-2
  - sdk install gradle
  - mkdir -p "$HOME/.sdkman/etc"
  - sdk use gradle
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
before_script:
  - ./gradlew up
  - sleep 3s
  - ./gradlew flywayMigrate -i
after_script:
  - ./gradlew rm
jobs:
  include:
    # java 8
    - stage: openjdk8
      jdk: openjdk8
      name: "Gradle Java 8 Build"
      script:
        - cd $TRAVIS_BUILD_DIR
        - gradle :wrapper
        - ./gradlew
        - java -jar build/libs/*-SNAPSHOT.jar
    - stage: openjdk8
      jdk: openjdk8
      name: "Gradle Java 8 Updates"
      script: cd $TRAVIS_BUILD_DIR && gradle :wrapper && ./gradlew dependencyUpdates -Drevision=release
    # java 11
    - stage: openjdk11
      jdk: openjdk11
      name: "Gradle Java 11 Build"
      script: cd $TRAVIS_BUILD_DIR ; gradle :wrapper ; ./gradlew ; java -jar build/libs/*-SNAPSHOT.jar
    - stage: openjdk11
      jdk: openjdk11
      name: "Gradle Java 11 Updates"
      script: cd $TRAVIS_BUILD_DIR ; gradle :wrapper ; ./gradlew dependencyUpdates -Drevision=release
cache:
  directories:
    - ~/.gradle
    - ~/.m2
  packages: true
